"""initial_migration

Revision ID: ccb66340423c
Revises: 
Create Date: 2026-05-12 23:26:19.988252
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccb66340423c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_email'), 'vendors', ['email'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_vendor_id'), 'chat_sessions', ['vendor_id'], unique=False)
    op.create_table('customers',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_vendor_id'), 'customers', ['vendor_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cogs_percentage', sa.Numeric(precision=5, scale=2), server_default='30.00', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_index(op.f('ix_menu_items_vendor_id'), 'menu_items', ['vendor_id'], unique=False)
    op.create_table('ml_run_logs',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('rmse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mae', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mape', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='ml_run_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_run_logs_vendor_id'), 'ml_run_logs', ['vendor_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('predicted_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_lower', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('confidence_upper', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_menu_item_id'), 'forecasts', ['menu_item_id'], unique=False)
    op.create_index('ix_forecasts_vendor_date', 'forecasts', ['vendor_id', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_vendor_id'), 'forecasts', ['vendor_id'], unique=False)
    op.create_table('orders',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='order_status', create_constraint=True), server_default='pending', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_vendor_id'), 'orders', ['vendor_id'], unique=False)
    op.create_index('ix_orders_vendor_status_date', 'orders', ['vendor_id', 'status', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_vendor_status_date', table_name='orders')
    op.drop_index(op.f('ix_orders_vendor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_forecasts_vendor_id'), table_name='forecasts')
    op.drop_index('ix_forecasts_vendor_date', table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_menu_item_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_ml_run_logs_vendor_id'), table_name='ml_run_logs')
    op.drop_table('ml_run_logs')
    op.drop_index(op.f('ix_menu_items_vendor_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_customers_vendor_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_chat_sessions_vendor_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_vendors_email'), table_name='vendors')
    op.drop_table('vendors')
    op.execute('DROP TYPE IF EXISTS ml_run_status')
    op.execute('DROP TYPE IF EXISTS order_status')
    # ### end Alembic commands ###
